#!/usr/bin/env python3
"""Legacy console build helper.

This repository standardizes on:
- macOS: onedir console bundle under release_console/SundayPhotoOrganizer/
- Windows: onedir console bundle under release_console/SundayPhotoOrganizer/
- Teacher-facing docs: md-only (no .txt)

Prefer using the maintained scripts under scripts/.
"""

import os
import sys
import subprocess
from pathlib import Path

def main():
    """Build console release using maintained scripts."""
    print("🚀 Building console release (preferred scripts)...")

    project_root = Path(__file__).resolve().parents[2]
    os.chdir(project_root)

    mac_script = project_root / "scripts" / "build_mac_app.sh"
    win_script = project_root / "scripts" / "build_windows_console_app.ps1"

    if sys.platform == "darwin":
        if not mac_script.exists():
            print(f"❌ Missing build script: {mac_script}")
            return False
        cmd = ["bash", str(mac_script)]
    elif sys.platform.startswith("win"):
        if not win_script.exists():
            print(f"❌ Missing build script: {win_script}")
            return False
        cmd = [
            "powershell",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(win_script),
        ]
    else:
        print("❌ Unsupported platform for packaged console release.")
        return False

    print("Command:", " ".join(cmd))
    result = subprocess.run(cmd, text=True)
    if result.returncode != 0:
        print(f"❌ Build failed (exit={result.returncode})")
        return False

    print("✅ Build finished.")
    print("📦 Output folder: release_console/SundayPhotoOrganizer/")
    print("📖 Usage (ZH): release_console/使用说明.md")
    print("📖 Usage (EN): release_console/USAGE_EN.md")
    return True

def create_console_guide():
    """Deprecated: docs are generated by scripts/build_mac_app.sh."""
    print("ℹ️ Deprecated: use scripts/build_mac_app.sh to generate release docs (md-only).")

def create_simple_launcher():
    """Deprecated: launchers are generated by scripts/build_mac_app.sh."""
    print("ℹ️ Deprecated: use scripts/build_mac_app.sh to generate launchers.")

if __name__ == "__main__":
    success = main()
    
    if success:
        print("\n🎊 Console release built successfully!")
        print("📂 release_console/ contains:")
        print("   - SundayPhotoOrganizer/ (onedir bundle)")
        print("   - 使用说明.md / USAGE_EN.md (md-only docs)")
    else:
        print("\n❌ 控制台版本打包失败，请检查错误信息")
        sys.exit(1)

    # Deprecated helpers kept for backward compatibility.
    create_simple_launcher()